language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  #- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsfml-dev
    - lcov
    - g++-4.9

script:
  - ls /usr/bin/g*
  - export CXX=g++-4.9
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
