language: cpp

compiler:
  - gcc
  - clang

env:

cache:
  - apt

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsfml-dev

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
