language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

#env:
#    COMPILER=g++-6

addons:
  apt:
    packages:
    - libsfml-dev
    - lcov
    - gcc-4.9

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
