language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y libsfml-dev

addons:
  apt:
    packages:
    - libsfml-dev
    - lcov

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
