language: cpp
dist: trusty
sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsfml-dev
    - lcov
    - g++-5

script:
  - mkdir -p build
  - cd build
  - export CXX=/usr/bin/g++-5
  - cmake ..
  - make
  - make test
