language: cpp

compiler:
  - gcc
  - clang

env:

cache:
  - apt

dist: trusty
sudo: required

before_install:
#  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get -qq update
  - sudo apt-get install -y libsfml-dev

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
