language: cpp
dist: trusty
sudo: true

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsfml-dev
    - lcov
    - g++-5
#    - gcc-5

before_install:
  - wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.8 main'
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y clang-3.8

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8"; fi

script:
  - mkdir -p build
  - cd build
  - cmake -DWIN32=false ..
  - make unit-tests
  - ./unit-tests
